-- TABLA USUARIOS
CREATE TABLE usuarios (
    usuario VARCHAR(50),        
    password VARCHAR(100),          
    email VARCHAR(50),                      
    fecha_cre TIMESTAMP        
)

-- TABLA DATOS
CREATE TABLE datos (
    usuario	VARCHAR(50)	,
    fecha_nacimiento	DATE	,
    edad	REAL	,
    estado_civil	VARCHAR(20)	,
    sexo	VARCHAR(10)	,
    escolaridad	INTEGER	,
    ocupacion	VARCHAR(30)	,
    clase_ingresos	VARCHAR(15)	,
    fatigabilidad	VARCHAR(15)	,
    resistencia	VARCHAR(5)	,
    deambulacion	VARCHAR(5)	,
    comorbilidad	VARCHAR(200)	,
    perdida_peso	VARCHAR(5)	,
    escala_frail	VARCHAR(15)	,
    hora_actual	TIMESTAMP	,
    hipertension	VARCHAR(5)	,
    angina	VARCHAR(5)	,
    insuficiencia_card	VARCHAR(5)	,
    infarto	VARCHAR(5)	,
    acv	VARCHAR(5)	,
    diabetes	VARCHAR(5)	,
    epoc	VARCHAR(5)	,
    artrosis	VARCHAR(5)	,
    osteoporosis	VARCHAR(5)	,
    continencia	VARCHAR(5)	,
    d_mentales	VARCHAR(5)	,
    fuma	VARCHAR(5)	,
    audicion	VARCHAR(20)	,
    vision	VARCHAR(20)	,
    equilibrio	VARCHAR(20)	,
    soporte_social	VARCHAR(15)	,
    repetir_3_palabras	VARCHAR(5)	,
    test_reloj	VARCHAR(10)	,
    estado_animo	VARCHAR(500)	,
    palabras_recordadas	INTEGER	,
    agente	VARCHAR(15)	,
    estado_salud	INTEGER	,
    actividad_fisica_2	INTEGER	,
    tiempo_caminar_promedio	REAL	,
    dolor	INTEGER	,
    usa_internet_email	INTEGER	,
    test_silla	INTEGER	,
    fatigabilidad_1	INTEGER	,
    obesidad_abdominal	REAL	,
    fatigabilidad_2	INTEGER	,
    caidas	INTEGER	,
    suenio	INTEGER	,
    peso	REAL	,
    altura	REAL	,
    indice_masa_corporal	REAL	,
    actividad_fisica_1	INTEGER	,
    soledad	INTEGER	,
    tiene_celular	INTEGER	,
    actividad_fisica_3	INTEGER	,
    alcohol	INTEGER	,
    memoria	INTEGER	,
    diag_fragilidad	VARCHAR(10)	
)

